{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggspectra
  version: {{ version|replace("-", "_") }}

source:
  fn: ggspectra_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggspectra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggspectra/ggspectra_{{ version }}.tar.gz
  sha256: 56849d17632350383f8fa413cbdd80369f776397a613584fdaf3dd5ae2eafddf

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr >=0.7.6
    - r-ggplot2 >=3.0.0
    - r-ggrepel >=0.8.0
    - r-lubridate >=1.7.4
    - r-photobiology >=0.9.24
    - r-photobiologywavebands >=0.4.2
    - r-scales >=1.0.0
    - r-tidyr >=0.8.1
  run:
    - r-base
    - r-dplyr >=0.7.6
    - r-ggplot2 >=3.0.0
    - r-ggrepel >=0.8.0
    - r-lubridate >=1.7.4
    - r-photobiology >=0.9.24
    - r-photobiologywavebands >=0.4.2
    - r-scales >=1.0.0
    - r-tidyr >=0.8.1

test:
  commands:
    - $R -e "library('ggspectra')"           # [not win]
    - "\"%R%\" -e \"library('ggspectra')\""  # [win]

about:
  home: https://www.r4photobiology.info, https://bitbucket.org/aphalo/ggspectra
  license: GPL (>= 2)
  summary: Additional annotations, and stats for plotting "light" spectra with 'ggplot2', together
    with specializations of ggplot() and plot() methods for spectral data stored in
    objects of the classes defined in package 'photobiology' and a plot() method for
    objects of class "waveband", also defined in package 'photobiology'. Part of the  'r4photobiology'
    suite, Aphalo P. J. (2015) <doi:10.19232/uv4pb.2015.1.14>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
