{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggspectra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggspectra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggspectra/ggspectra_{{ version }}.tar.gz
  sha256: 56849d17632350383f8fa413cbdd80369f776397a613584fdaf3dd5ae2eafddf

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.8.0.1
    - r-ggplot2 >=3.1.0
    - r-ggrepel >=0.8.0
    - r-lubridate >=1.7.4
    - r-photobiology >=0.9.26
    - r-photobiologywavebands >=0.4.2
    - r-scales >=1.0.0
    - r-tidyr >=0.8.2
  run:
    - r-base
    - r-dplyr >=0.8.0.1
    - r-ggplot2 >=3.1.0
    - r-ggrepel >=0.8.0
    - r-lubridate >=1.7.4
    - r-photobiology >=0.9.26
    - r-photobiologywavebands >=0.4.2
    - r-scales >=1.0.0
    - r-tidyr >=0.8.2

test:
  commands:
    - $R -e "library('ggspectra')"           # [not win]
    - "\"%R%\" -e \"library('ggspectra')\""  # [win]

about:
  home: https://www.r4photobiology.info, https://bitbucket.org/aphalo/ggspectra
  license: GPL (>= 2)
  summary: Additional annotations, stats, geoms and scales for plotting  "light" spectra with
    'ggplot2', together with specializations of ggplot() and autoplot() methods for
    spectral data and waveband definitions stored in objects of classes defined in package
    'photobiology'. Part of the  'r4photobiology' suite, Aphalo P. J. (2015) <doi:10.19232/uv4pb.2015.1.14>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggspectra
# Type: Package
# Title: Extensions to 'ggplot2' for Radiation Spectra
# Version: 0.3.2
# Date: 2019-02-19
# Authors@R:  c( person("Pedro J.", "Aphalo", email = "pedro.aphalo@helsinki.fi", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-3385-972X")), person("Titta K.", "Kotilainen", role = "ctb", comment = c(ORCID = "0000-0002-2822-9734")) )
# Maintainer: Pedro J. Aphalo <pedro.aphalo@helsinki.fi>
# Description: Additional annotations, stats, geoms and scales for plotting  "light" spectra with 'ggplot2', together with specializations of ggplot() and autoplot() methods for spectral data and waveband definitions stored in objects of classes defined in package 'photobiology'. Part of the  'r4photobiology' suite, Aphalo P. J. (2015) <doi:10.19232/uv4pb.2015.1.14>.
# License: GPL (>= 2)
# LazyData: TRUE
# LazyLoad: TRUE
# ByteCompile: TRUE
# Depends: R (>= 3.4.0), photobiology (>= 0.9.26), ggplot2 (>= 3.1.0)
# Imports: photobiologyWavebands (>= 0.4.2), scales (>= 1.0.0), ggrepel (>= 0.8.0), dplyr (>= 0.8.0.1), lubridate (>= 1.7.4), tidyr (>= 0.8.2)
# Suggests: knitr (>= 1.21), rmarkdown (>= 1.11)
# URL: https://www.r4photobiology.info, https://bitbucket.org/aphalo/ggspectra
# BugReports: https://bitbucket.org/aphalo/ggspectra
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-02-20 11:51:42 UTC; aphalo
# Author: Pedro J. Aphalo [aut, cre] (<https://orcid.org/0000-0003-3385-972X>), Titta K. Kotilainen [ctb] (<https://orcid.org/0000-0002-2822-9734>)
# Repository: CRAN
# Date/Publication: 2019-02-20 13:20:03 UTC
