appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: G+KYs5dgthzFBilz4eKNXu2wSQhftXolyayYRoTobbZ7Kh902/tsiZBiYn4rT/YyoQ76Pwq8cXKXNB5sb57gJqva28sw5CwUtdvwZeeJcv+LtTJAbKDQOSobVuuR+vcWdU4UJBy/wJwL9vQfqZqb+pF7H8vIzgplD7zGNuhlGY0vm0aOJyhXa9OyIM8XKrMX2HqRS3hV1hRHp2jTaGA50f9H0rc1J9kzN8uG0SlfLeszpUY7s4+D7u81Wl6ONcVKm5mdl0Elc7YskqsUSyBSqyU0HDYreJXwcpCnDJ5JliQEqtv9IzMUuLrabQlhHm/62BXtfDI95BcOXWp0LLW9e6yo0ZwN2Zi6zMn7MsQnK5jMoX+X2HRGZ/3Gj1RZHoFQhpchJyOpXwvGI1B2NI3RFoZSQ/RsK3765lEia5jSfjyQzp0j36Ont7VaQgS5IxKTI0KlOo6JrM7XEK3z5IScHNG2TOBuZIUrwIqNrJ7LYOxiwpCX+dNfMjk5vptnZzy/S1iixgsNuqZjYCp91uFoXmZpL0efyQDZYAc1Q2fyyUQBLZFB9gxUF00MInT7y5xON92psa/k1VQP2m6FkFIFR9a/lGprnWhd2VlZ6K74F7nmfVeI7c5NEO1J1zu7kECRd+QpkcOXrIJM53NqitYLwzTTjX87KqVVHsJQ6R4Xz3A=}
bot:
  automerge: true
