travis:
  secure:
    BINSTAR_TOKEN: yAZ5yfjn0l59OxYI5Ak/D2LFP4Lkn5gTQ9GbCf0SFoGmNJwODPJgb+v8UXkzBdwXcR+gi0yVsjIDZ/coZ3qZXVoztp9rSITemsilLGk3d+HvG4GOiPe7WOTJmtzmCLzMINZkZ3+2uCHmabyFUEhFnAbDjgHFxi7rjqmcOjdL6dKxX3cveL653naA1dLJW8IwDrTdaCLNNwDgnGZpFRXA34F/6hZWEWpJlDreZ+3DCfXgfmjv5VtSsp2hpaKx9QZ4DnQPjpJWoXT7JQux8L1P2+qCU8uy5O+J5R2VH4QnVGPAMHzdLnf9VvjytaEkI+N1kt7IdqA0EgyBdKPDmNwcNebWF5amxs8Iz+QClT9J+KA1z0qMzYl+364hfLmbFMWm5/EzIwT7z+/bqa4f3gAI4Lx6AtYh/VvZEKcbneQzxBXJK2J4QdH5IAZgd6wkD6xev8PmiJO9+9kSYzWIw6Pqq9hY7o4pU0QuVMdRKohwHhaII1RAcDNJYT/4nl9l2+53gprXr2HiWRmReTtYbnAbCXb8KNL9yGklzmbWubWd/7t2Z1UGGBysrW/GFCQ1Kd4GtSUb/cNb0sSfQ2sfYCZ/tO5Sc3UyeI0uKmr1ieQNG3Dus8sYCN9n0x9yVv7jtT4FgS5jCLcmNeg6Fgd2PhdyOn1cCg6FekfuLPDF8Kx490M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
